[tool.pytest.ini_options]
# We want errors to fail loudly to not miss any exceptions in the background
# The latter part shows the duration of the slowest tests
# -v prints the test case names to see deadlocks
addopts = "-Werror --color=yes --cov=ros2_easy_test --doctest-modules --cov-report html --durations=0 --durations-min=3.0 -v"
testpaths = [
    "ros2_easy_test/ros2_easy_test",  # for the doctests
    "ros2_easy_test/tests",  # for the actual tests
]

[tool.ruff]
line-length = 110
# The lowest supported version
target-version = "py38"
exclude = ["build/**", "install/**"]  # Gets created by the CI pipeline

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP"]

[tool.ruff.format]
docstring-code-format = true

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "rclpy.*",  # For the CI pipeline to work
    "launch.*",
    "example_interfaces.*",
    "std_msgs.*",
]
ignore_missing_imports = true
